[package]
name = "arduino-password-vault"
version = "0.1.0"
edition = "2024"
authors = ["Lukas Drobek"]
description = "Interactive CLI application for an Arduino-based password vault"

[dependencies]
serialport="4.7.1"